jobs:
 build:
   machine: true
   steps:
    - checkout
    - run: docker build -t nivankovic/docker-react -f Dockerfile.dev .
    - run: docker run -e CI=true nivankovic/docker-react npm run test -- --coverage
